config/routes.rb
Rails.application.routes.draw do
  resources :backgrounds
  resources :cards
  resources :emotes
  get 'static_pages/about'
  root "pages#home"
  get 'pages/home', to: 'pages#home'
  #root :to => "games#index"

  resources :games do
    resources :comments, only: [:create]
    member do 
      post 'like'
    end
  end

  get 'search_pages/search'
  post 'search_pages/search'
  get '/register', to: 'gamers#new'
  get "/signup", to: 'gamers#new'
  get '/login', to: 'sessions#new'
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"
  resources :gamers, except: [:new]

  resources :games
  resources :genres
  resources :companies
  mount ActionCable.server => '/cable'
  get '/chat', to: 'chatrooms#show'
  resources :messages, only: [:create]
  get '/games/stats/:id', to: 'games#stats'
  get '/games/loadmoresysreq/:processor/:memory/:graphic/:offset/:limit', to: 'games#loadmoresysreq'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/background.rb
class Background < ApplicationRecord
  belongs_to :game, optional: true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :game
  #validates :name, presence: true
  #validates :price, presence: true
  #validates :image, presence: true
  #validates :game_id, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :gamer
  belongs_to :game 
  # validates :description, presence: true, length: { minimum: 4, maximum: 140 }
  # validates :gamer_id, presence: true
  # validates :game_id, presence: true
  # default_scope -> { order(updated_at: :desc)}
end

app/models/company.rb
class Company < ApplicationRecord
    has_and_belongs_to_many :games
end

app/models/emote.rb
class Emote < ApplicationRecord
  belongs_to :game
end

app/models/game.rb
class Game < ApplicationRecord

  has_one :system_requirement

  has_many :backgrounds
  has_many :cards
  has_many :emotes

  has_and_belongs_to_many :companies

  has_many :game_ratings
  has_many :gamers, through: :game_ratings
  
  has_many :comments, dependent: :destroy
  has_many :gamers, through: :comments

  has_many :price_histories

  has_and_belongs_to_many :genres
  has_and_belongs_to_many :gamers
  has_many :likes, dependent: :destroy
  def thumbs_up_total
    self.likes.where(like: true).size
  end
  
  def thumbs_down_total
    self.likes.where(like: false).size    
  end
 
  validates :steam_id, presence: true, numericality: {only_integer: true}, uniqueness: true
  validates :name, presence: true
  validates :price, presence: true, numericality: true
  validates :release_date, presence: true, timeliness: { type: :date }
  validates :description, presence: true
  validates :image, url: true

  def self.sysReq(processor_rank, memory_rank, graphic_rank, offset, limit)
      sql = """
	    SELECT games.id, games.name, games.steam_id, games.price, games.release_date
	    FROM games
	    INNER JOIN system_requirements
	    ON games.id = system_requirements.game_id
	    INNER JOIN processors
	    ON system_requirements.processor_id = processors.id
	    WHERE processors.rank >= #{processor_rank}
	    INTERSECT
	    SELECT games.id, games.name, games.steam_id, games.price, games.release_date
	    FROM games
	    INNER JOIN system_requirements
	    ON games.id = system_requirements.game_id
	    INNER JOIN memories
	    ON system_requirements.memory_id = memories.id
	    WHERE memories.rank >= #{memory_rank}
	    INTERSECT
	    SELECT games.id, games.name, games.steam_id, games.price, games.release_date
	    FROM games
	    INNER JOIN system_requirements
	    ON games.id = system_requirements.game_id
	    INNER JOIN graphics
	    ON system_requirements.graphic_id = graphics.id
	    WHERE graphics.rank >= #{graphic_rank} offset #{offset} limit #{limit}
      """
      ActiveRecord::Base.connection.select_rows(sql)
  end


end

app/models/gamer.rb
class Gamer < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :gamername, presence: true, length: { maximum: 30 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 5 },allow_nil: true
  has_many :messages, dependent: :destroy
  # has_many :comments, dependent: :destroy

  has_many :game_ratings
  has_many :games, through: :game_ratings

  has_many :comments
  has_many :games, through: :comments, dependent: :destroy

  has_and_belongs_to_many :games
  has_many :likes, dependent: :destroy
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_and_belongs_to_many :games
end

app/models/graphic.rb
class Graphic < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :gamer
    belongs_to :game
    
    validates_uniqueness_of :gamer, scope: :game
  end

app/models/memory.rb
class Memory < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :gamer
  validates :content, presence: true
  validates :gamer_id, presence: true
  def self.most_recent
    order(:created_at).last(20)
  end
end

app/models/price_history.rb
class PriceHistory < ApplicationRecord
  belongs_to :game
end

app/models/processor.rb
class Processor < ApplicationRecord
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :gamer
end

app/models/system_requirement.rb
class SystemRequirement < ApplicationRecord
  belongs_to :game
  belongs_to :processor
  belongs_to :graphic
  belongs_to :memory
end

app/controllers/backgrounds_controller.rb
class BackgroundsController < ApplicationController
  skip_before_action :verify_authenticity_token, raise: false
  before_action :set_background, only: [:show, :edit, :update, :destroy]
  before_action :require_admin, only: [:create, :new, :edit, :update, :destroy]

  # GET /backgrounds
  # GET /backgrounds.json
  def index
    @backgrounds = Background.all
  end

  # GET /backgrounds/1
  # GET /backgrounds/1.json
  def show
  end

  # GET /backgrounds/new
  def new
    @background = Background.new
  end

  # GET /backgrounds/1/edit
  def edit
  end

  # POST /backgrounds
  # POST /backgrounds.json
  def create
    @background = Background.new(background_params)

    respond_to do |format|
      if @background.save
        game = Game.find(params[:background][:game_id])
	game.backgrounds << @background
        format.html { redirect_to @background, notice: 'Background was successfully created.' }
        format.json { render :show, status: :created, location: @background }
      else
        format.html { render :new }
        format.json { render json: @background.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /backgrounds/1
  # PATCH/PUT /backgrounds/1.json
  def update
    respond_to do |format|
      if @background.update(background_params)
        format.html { redirect_to @background, notice: 'Background was successfully updated.' }
        format.json { render :show, status: :ok, location: @background }
      else
        format.html { render :edit }
        format.json { render json: @background.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /backgrounds/1
  # DELETE /backgrounds/1.json
  def destroy
    @background.destroy
    respond_to do |format|
      format.html { redirect_to backgrounds_url, notice: 'Background was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_background
      @background = Background.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def background_params
      params.require(:background).permit(:name, :price, :image, :game_id)
    end
end

app/helpers/backgrounds_helper.rb
module BackgroundsHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/backgrounds/_form.html.erb
<%= form_with(model: background, local: true) do |form| %>
  <% if background.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(background.errors.count, "error") %> prohibited this background from being saved:</h2>

      <ul>
      <% background.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_area :name, id: :background_name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price, id: :background_price %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_area :image, id: :background_url %>
  </div>

  <div class="field">
    <%= form.label :game_id %>
    <%= form.number_field :game_id, id: :background_appid %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/backgrounds/edit.html.erb
<h1>Editing Background</h1>

<%= render 'form', background: @background %>

<%= link_to 'Show', @background %> |
<%= link_to 'Back', backgrounds_path %>

app/views/backgrounds/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-center">Backgrounds</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Image</th>
      <% if logged_in? && current_gamer.admin? %>
      <th colspan="2">Options</th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @backgrounds.each do |background| %>
      <tr>
        <td><%= link_to background.name, background %></td>
        <td><%= background.price %></td>
	<td><img style="max-width: 200px" src="<%= background.image %>"></td>
	<% if logged_in? && current_gamer.admin? %>
        <td><%= link_to 'Edit', edit_background_path(background) %></td>
        <td><%= link_to 'Destroy', background, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	<% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if logged_in? && current_gamer.admin? %>
<%= link_to 'New Background', new_background_path %>
<% end %>

app/views/backgrounds/new.html.erb
<h1>New Background</h1>

<%= render 'form', background: @background %>

<%= link_to 'Back', backgrounds_path %>

app/views/backgrounds/show.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-center">background <span class="game-header"><%= @background.name %></span> for <span class="game-header"><%= @background.game.name %></span></h1>

<p class="text-center">
  <strong>Price:</strong>
  <%= @background.price %>
</p>

<p class="text-center">
  <img style="max-width: 500px" src="<%= @background.image %>">
</p>

<p class="text-center">
  <a href="/games/<%= @background.game_id %>"">[visit <%= @background.game.name %> page]</a>
</p>

<% if logged_in? && current_gamer.admin? %>
<%= link_to 'Edit', edit_background_path(@background) %> |
<%= link_to 'Back', backgrounds_path %>
<% end %>