config/routes.rb
Rails.application.routes.draw do
  resources :backgrounds
  resources :cards
  resources :emotes
  get 'static_pages/about'
  root "pages#home"
  get 'pages/home', to: 'pages#home'
  #root :to => "games#index"

  resources :games do
    resources :comments, only: [:create]
    member do 
      post 'like'
    end
  end

  get 'search_pages/search'
  post 'search_pages/search'
  get '/register', to: 'gamers#new'
  get "/signup", to: 'gamers#new'
  get '/login', to: 'sessions#new'
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"
  resources :gamers, except: [:new]

  resources :games
  resources :genres
  resources :companies
  mount ActionCable.server => '/cable'
  get '/chat', to: 'chatrooms#show'
  resources :messages, only: [:create]
  get '/games/stats/:id', to: 'games#stats'
  get '/games/loadmoresysreq/:processor/:memory/:graphic/:offset/:limit', to: 'games#loadmoresysreq'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/game.rb
class Game < ApplicationRecord

  has_one :system_requirement

  has_many :backgrounds
  has_many :cards
  has_many :emotes

  has_and_belongs_to_many :companies

  has_many :game_ratings
  has_many :gamers, through: :game_ratings
  
  has_many :comments, dependent: :destroy
  has_many :gamers, through: :comments

  has_many :price_histories

  has_and_belongs_to_many :genres
  has_and_belongs_to_many :gamers
  has_many :likes, dependent: :destroy
  def thumbs_up_total
    self.likes.where(like: true).size
  end
  
  def thumbs_down_total
    self.likes.where(like: false).size    
  end
 
  validates :steam_id, presence: true, numericality: {only_integer: true}, uniqueness: true
  validates :name, presence: true
  validates :price, presence: true, numericality: true
  validates :release_date, presence: true, timeliness: { type: :date }
  validates :description, presence: true
  validates :image, url: true

  def self.sysReq(processor_rank, memory_rank, graphic_rank, offset, limit)
      sql = """
	    SELECT games.id, games.name, games.steam_id, games.price, games.release_date
	    FROM games
	    INNER JOIN system_requirements
	    ON games.id = system_requirements.game_id
	    INNER JOIN processors
	    ON system_requirements.processor_id = processors.id
	    WHERE processors.rank >= #{processor_rank}
	    INTERSECT
	    SELECT games.id, games.name, games.steam_id, games.price, games.release_date
	    FROM games
	    INNER JOIN system_requirements
	    ON games.id = system_requirements.game_id
	    INNER JOIN memories
	    ON system_requirements.memory_id = memories.id
	    WHERE memories.rank >= #{memory_rank}
	    INTERSECT
	    SELECT games.id, games.name, games.steam_id, games.price, games.release_date
	    FROM games
	    INNER JOIN system_requirements
	    ON games.id = system_requirements.game_id
	    INNER JOIN graphics
	    ON system_requirements.graphic_id = graphics.id
	    WHERE graphics.rank >= #{graphic_rank} offset #{offset} limit #{limit}
      """
      ActiveRecord::Base.connection.select_rows(sql)
  end


end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  skip_before_action :verify_authenticity_token, raise: false
  before_action :set_game, only: [:show, :edit, :update, :destroy, :like]
  before_action :require_user, except: [:index, :show, :like, :stats, :loadmoresysreq]
  before_action :require_admin, only: [:create, :new, :edit, :update, :destroy]
  before_action :require_user_like, only: [:like]

  # GET /games/stats
  def stats
    game = Game.find(params[:id])
    likes = game.likes.where(like: true).count
    dislikes = game.likes.where(like: false).count
    render html: "likes:#{likes} | dislikes:#{dislikes}"
  end

  def loadmoresysreq
    games = Game.sysReq(params[:processor], params[:memory], params[:graphic], params[:offset], params[:limit])
    html = ''
    for game in games
      html += '<tr>'
      html += '<td><a href="/games/' + game[0].to_s + '">' + game[1] + '</a></td>'
      html += '<td><a target="_blank" href="https://store.steampowered.com/app/' + game[2].to_s + '">' + game[2].to_s + '</a></td>'
      html += '<td>' + game[3].to_s + '</td>'
      html += '<td>' + game[4] + '</td>'
      html += '</tr>'
    end
    render html: html
  end

  # GET /games
  # GET /games.json
  def index
    @games = Game.all.paginate(page: params[:page], per_page: 100)
    #@games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
    #fresh_when last_modified: @game.updated_at
    @comment = Comment.new
    @comments = @game.comments.paginate(page: params[:page], per_page: 5)
    @price_histories = @game.price_histories.order('time DESC')
    @system_requirement = @game.system_requirement
    @backgrounds = @game.backgrounds
    @cards = @game.cards
    @emotes = @game.emotes
    #@comments = @game.comments
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
	# start for mtm - many to many
	if params[:game][:genre_ids]
	  params[:game][:genre_ids].each do |genre_id|
	    unless genre_id.empty?
	      genre = Genre.find(genre_id)
	      @game.genres << genre
	    end
	  end
	end
	if params[:game][:company_ids]
	  params[:game][:company_ids].each do |company_id|
	    unless company_id.empty?
	      company = Company.find(company_id)
	      @game.companies << company
	    end
	  end
	end
	# end for mtm
	processor_id = params[:game][:processor_id]
	memory_id = params[:game][:memory_id]
	graphic_id = params[:game][:graphic_id]
	if (processor_id != 0) and (memory_id != 0) and (graphic_id != 0)
	  @game.system_requirement = SystemRequirement.new({processor_id: processor_id, memory_id: memory_id, graphic_id: graphic_id})
	else
	  @game.system_requirement = SystemRequirement.new({processor_id: 1, memory_id: 1, graphic_id: 1})
	end
	@game.system_requirement.save()
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end
  def like
    like = Like.create(like: params[:like], gamer: current_gamer, game: @game)
    if like.valid?
      flash[:success] = "Your selection was succesful"
      redirect_back fallback_location: root_path
    else
      flash[:danger] = "You can only like/dislike a game once"
      redirect_back fallback_location: root_path
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
	# start for mtm
	@game.genres.delete_all
	if params[:game][:genre_ids]
	  params[:game][:genre_ids].each do |genre_id|
	    unless genre_id.empty?
	      genre = Genre.find(genre_id)
	      @game.genres << genre
	    end
	  end
	end
	@game.companies.delete_all
	if params[:game][:company_ids]
	  params[:game][:company_ids].each do |company_id|
	    unless company_id.empty?
	      company = Company.find(company_id)
	      @game.companies << company
	    end
	  end
	end
	# end for mtm
	processor_id = params[:game][:processor_id]
	memory_id = params[:game][:memory_id]
	graphic_id = params[:game][:graphic_id]
	sys_req = @game.system_requirement
	if processor_id != 0
	  sys_req.processor_id = processor_id
	end
	if memory_id != 0
	  sys_req.memory_id = memory_id
	end
	if graphic_id != 0
	  sys_req.graphic_id = graphic_id
	end
	sys_req.save
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    flash[:danger] = "This Game has been removed"
    redirect_to root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:steam_id, :name, :price, :release_date, :description, :image)
    end
    def require_user_like
      if !logged_in?
        flash[:danger] = "You must be logged in to perform that action"
        redirect_back fallback_location: root_path
      end
    end

end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_with(model: game, local: true) do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :steam_id %>
    <%= form.number_field :steam_id, id: :game_steam_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :game_name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :game_price %>
  </div>

  <div class="field">
    <%= form.label :release_date %>
    <%= form.date_select :release_date, id: :game_release_date %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :game_description %>
  </div>

  <%= form.label :genres %>
  <% Genre.all.each do |genre| %>
    <span><input type="checkbox" name="game[genre_ids][]" value="<%= genre.id %>" <% if game.genres.pluck(:name).include?(genre.name) %>checked<% end %>><%= genre.name %></span>&nbsp;&nbsp;&nbsp;&nbsp;
  <% end %>

  <div class="clearfix"><br></div>

  <%= form.label :companies %>
  <% Company.all.each do |company| %>
    <span><input type="checkbox" name="game[company_ids][]" value="<%= company.id %>" <% if game.companies.pluck(:name).include?(company.name) %>checked<% end %>><%= company.name %></span>&nbsp;&nbsp;&nbsp;&nbsp;
  <% end %>


  <div class="clearfix"><br></div>

  <%= form.label :system_requirements %>
  <% if game.system_requirement %>
  <table>
    <tr>
      <td>Processor</td>
      <td>
	<select name="game[processor_id]">
	  <option value="0">--</option>
	  <% Processor.all.each do |processor| %>
	    <option value="<%= processor.id %>" <% if game.system_requirement.processor.name == processor.name %>selected<% end %>><%= processor.name %></option>
	<% end %>
	</select>
      </td>
    </tr>
    <tr>
      <td>Memory</td>
      <td>
	<select name="game[memory_id]">
	  <option value="0">--</option>
	  <% Memory.all.each do |memory| %>
	    <option value="<%= memory.id %>" <% if game.system_requirement.memory.name == memory.name %>selected<% end %>><%= memory.name %></option>
	<% end %>
	</select>
      </td>
    </tr>
    <tr>
      <td>Graphics Card</td>
      <td>
	<select name="game[graphic_id]">
	  <option value="0">--</option>
	  <% Graphic.all.each do |graphic| %>
	    <option value="<%= graphic.id %>" <% if game.system_requirement.graphic.name == graphic.name %>selected<% end %>><%= graphic.name %></option>
	<% end %>
	</select>
      </td>
    </tr>
  </table>
  <% else %>
  <table>
    <tr>
      <td>Processor</td>
      <td>
	<select name="game[processor_id]">
	  <option value="0">--</option>
	  <% Processor.all.each do |processor| %>
	    <option value="<%= processor.id %>"><%= processor.name %></option>
	<% end %>
	</select>
      </td>
    </tr>
    <tr>
      <td>Memory</td>
      <td>
	<select name="game[memory_id]">
	  <option value="0">--</option>
	  <% Memory.all.each do |memory| %>
	    <option value="<%= memory.id %>"><%= memory.name %></option>
	<% end %>
	</select>
      </td>
    </tr>
    <tr>
      <td>Graphics Card</td>
      <td>
	<select name="game[graphic_id]">
	  <option value="0">--</option>
	  <% Graphic.all.each do |graphic| %>
	    <option value="<%= graphic.id %>"><%= graphic.name %></option>
	<% end %>
	</select>
      </td>
    </tr>
  </table>
  <% end %>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image, id: :game_image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<% provide(:title, 'Games') %>
<p id="notice"><%= notice %></p>

<h1 class="text-center">Games</h1>

<div class="text-center">
</div>
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Steam ID</th>
      <th>Price (USD)</th>
      <th>Release date</th>
      <% if logged_in? && current_gamer.admin? %>
      <th colspan="2">Options</th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= link_to game.name, game %>
        <div class="pull-right liking">
          <%= link_to like_game_path(game, like: true), method: :post do %>
            <i class="glyphicon glyphicon-thumbs-up"></i> 
          <% end %> <%#= game.thumbs_up_total %> || 
          <%= link_to like_game_path(game, like: false), method: :post do %>
            <i class="glyphicon glyphicon-thumbs-down"></i>
          <% end %> <%#= game.thumbs_down_total %>
	  <span id="game_<%= game.id%>">[stat]</span>
          </div>
        </td>
  <td><%= link_to game.steam_id, "https://store.steampowered.com/app/#{game.steam_id}", target: "_blank" %>
  </td>
        <td><%= game.price %></td>
  <td><%= game.release_date %></td>
   <% if logged_in? && current_gamer.admin? %>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
      </tr>
  <% end %>
  </tbody>
</table>
<div class="text-center">
</div>

<br>

<% if session[:gamer_id] and session[:user_type] == "admin" %>
<%= link_to 'New Game', new_game_path %>
<% end %>

<script>
$('span[id ^= "game_"]').hover(function(e){
    var gameID = e.target.id.substring(5);
    var space = $(this);
    $.ajax({
	'type': 'GET',
	'url': '/games/stats/' + gameID,
	'dataType': 'html',
	'success': function(data){
	    space.html(data);
	}
    });
}, function(){
    $(this).html('[stat]');
});
</script>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<% provide(:title, @game.name) %>
<p id="notice"><%= notice %></p>

<h1 class="text-center game-header"><%= @game.name %></h1>

<%= image_tag(@game.image, alt: "game banner", class: "center-block game-banner") %>

<p class="pull-left"><strong>Steam ID:</strong> <%= link_to @game.steam_id, "https://store.steampowered.com/app/#{@game.steam_id}", target: "_blank" %></p>

<p class="pull-right">
  <strong>Release date:</strong>
  <%= @game.release_date %>
</p>

<div class="clearfix clearfix-divider"></div>

<p class="text-center game-price">
  <strong>Current Price (USD):</strong>
  <%= @game.price %>
</p>

<p class="text-center">
  <strong>Developed By</strong><br/><br/>
  <% @game.companies.each do |company| %>
    <span class="label label-primary label-company"><%= link_to company.name, company%></span>
  <% end %>
</p>

<div class="clearfix clearfix-divider"></div>

<p class="text-center game-description">
  <%= @game.description %>
</p>


<p class="text-center clearfix-divider">
  <strong>Genre(s)</strong><br/><br/>
  <% @game.genres.each do |genre| %>
    <span class="badge badge-success badge-genre"><%= link_to genre.name, genre%></span>
  <% end %>
</p>

<p class="text-center">
<strong>System Requirements</strong>
<% if @system_requirement %>
<table class="table table-bordered">
  <tr><td><strong>Processor</strong></td><td><% if @game.system_requirement.processor %><%= @game.system_requirement.processor.name %><% end %></td></tr>
  <tr><td><strong>Memory</strong></td><td><% if @game.system_requirement.memory %><%= @game.system_requirement.memory.name %><% end %></td></tr>
  <tr><td><strong>Graphics Card</strong></td><td><% if @game.system_requirement.graphic %><%= @game.system_requirement.graphic.name %><% end %></td></tr>
</table>
<% end %>
</p>

<h2 class="text-center">Backgrounds</h2>
<% @backgrounds.each do |background| %>
<div class="col-md-4">
<p><img src="https://steamcommunity-a.akamaihd.net/economy/image/<%= background.image %>" class="img-responsive"></p>
<div class="text-center"><p class="label label-success price-label">$<%= background.price %></p></div>
<p class="text-center"><strong><%= background.name %></strong></p>
</div>
<% end %>

<div class="clearfix"></div>

<h2 class="text-center">Cards</h2>
<% @cards.each do |card| %>
<div class="col-md-4">
<p><img src="https://steamcommunity-a.akamaihd.net/economy/image/<%= card.image %>" class="img-responsive"></p>
<div class="text-center"><p class="label label-success price-label">$<%= card.price %></p></div>
<p class="text-center"><strong><%= card.name %></strong></p>
</div>
<% end %>

<div class="clearfix"></div>

<h2 class="text-center">Emotes</h2>
<% @emotes.each do |emote| %>
<div class="col-md-4">
<p><img src="https://steamcommunity-a.akamaihd.net/economy/image/<%= emote.image %>" class="img-responsive"></p>
<div class="text-center"><p class="label label-success price-label">$<%= emote.price %></p></div>
<p class="text-center"><strong><%= emote.name %></strong></p>
</div>
<% end %>

<div class="clearfix"></div>


<div class="wrapper">
  <h2 class="text-center">Game Price</h2>
  <canvas id="myChart" width="1600" height="500"></canvas>
</div>

<div class="clearfix clearfix-divider"></div>

<% if logged_in? && current_gamer.admin? %>
<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Destroy', @game, method: :delete, data: {confirm: 'Are you sure?'} %> |
<% end %>
<%= link_to 'Back', games_path %>

<% if logged_in? %>
<div class="row">
  <div class="row col-md-8 col-md-offset-2">
    <%= link_to like_game_path(@game, like: true), method: :post do %>
      <i class="glyphicon glyphicon-thumbs-up"></i> 
    <% end %> <%= @game.thumbs_up_total %> || 
    <%= link_to like_game_path(@game, like: false), method: :post do %>
      <i class="glyphicon glyphicon-thumbs-down"></i>
    <% end %> <%= @game.thumbs_down_total %>
  </div>
</div>
<% end %>


<% if @game.comments != 0 %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h3>Prior Comments: </h3>
        <div id="messages">
          <%= render partial: 'comments/comments', object: @comments %>
        </div>
    </div>
  </div>
<% else %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h3>No Comments Yet!</h3>
    </div>
  </div>
<% end %>

<% if logged_in? %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h3>Comments: </h3>
      <hr />
      <%= form_for([@game, @comment], :html => {class: "form-horizontal", 
         role: "form"}) do |f| %>
        <div class="form-group">
          <div class="control-label col-md-2">
            <%= f.label :description, "Comment" %>
          </div>
          <div class="col-md-8">
            <%= f.text_area :description, rows: 8, class: "form-control", 
            placeholder: "Enter Comment Here" %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-md-offset-2 col-md-10">
            <%= f.submit "Submit Comment", 
            class: "btn btn-primary btn-lg btn-xlarge" %>
          </div>
        </div>
      <% end %>
      <hr />
    </div>
  </div>
<% end %>

<script>
var time = [];
var price = [];
<% @price_histories.each do |price_history| %>
  time.push('<%= price_history.time %>');
  price.push(<%= price_history.price %>);
<% end %>
var ctx = document.getElementById("myChart");
var myChart = new Chart(ctx, {
  type: 'line',
  data: {
    labels: time,
    datasets: [
      { 
        data: price,
	label: 'price',
	steppedLine: true,
	borderColor: "#3e95cd",
	fill: false
      }
    ]
  },
options: {
    scales: {
      xAxes: [{
        type: 'time',
	      time: {
	      	displayFormats: {
			'millisecond': 'MMM DD',
           'second': 'MM-DD-YYYY',
           'minute': 'MM-DD-YYYY',
           'hour': 'MM-DD-YYYY',
           'day': 'MM-DD-YYYY',
           'week': 'MM-DD-YYYY',
           'month': 'MM-DD-YYYY',
           'quarter': 'MM-DD-YYYY',
           'year': 'MM-DD-YYYY',
		}
	      }
      }],
    },
  }
});
</script>