config/routes.rb
Rails.application.routes.draw do
  resources :backgrounds
  resources :cards
  resources :emotes
  get 'static_pages/about'
  root "pages#home"
  get 'pages/home', to: 'pages#home'
  #root :to => "games#index"

  resources :games do
    resources :comments, only: [:create]
    member do 
      post 'like'
    end
  end

  get 'search_pages/search'
  post 'search_pages/search'
  get '/register', to: 'gamers#new'
  get "/signup", to: 'gamers#new'
  get '/login', to: 'sessions#new'
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"
  resources :gamers, except: [:new]

  resources :games
  resources :genres
  resources :companies
  mount ActionCable.server => '/cable'
  get '/chat', to: 'chatrooms#show'
  resources :messages, only: [:create]
  get '/games/stats/:id', to: 'games#stats'
  get '/games/loadmoresysreq/:processor/:memory/:graphic/:offset/:limit', to: 'games#loadmoresysreq'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/background.rb
class Background < ApplicationRecord
  belongs_to :game, optional: true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :game
  #validates :name, presence: true
  #validates :price, presence: true
  #validates :image, presence: true
  #validates :game_id, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :gamer
  belongs_to :game 
  # validates :description, presence: true, length: { minimum: 4, maximum: 140 }
  # validates :gamer_id, presence: true
  # validates :game_id, presence: true
  # default_scope -> { order(updated_at: :desc)}
end

app/models/company.rb
class Company < ApplicationRecord
    has_and_belongs_to_many :games
end

app/models/emote.rb
class Emote < ApplicationRecord
  belongs_to :game
end

app/models/game.rb
class Game < ApplicationRecord

  has_one :system_requirement

  has_many :backgrounds
  has_many :cards
  has_many :emotes

  has_and_belongs_to_many :companies

  has_many :game_ratings
  has_many :gamers, through: :game_ratings
  
  has_many :comments, dependent: :destroy
  has_many :gamers, through: :comments

  has_many :price_histories

  has_and_belongs_to_many :genres
  has_and_belongs_to_many :gamers
  has_many :likes, dependent: :destroy
  def thumbs_up_total
    self.likes.where(like: true).size
  end
  
  def thumbs_down_total
    self.likes.where(like: false).size    
  end
 
  validates :steam_id, presence: true, numericality: {only_integer: true}, uniqueness: true
  validates :name, presence: true
  validates :price, presence: true, numericality: true
  validates :release_date, presence: true, timeliness: { type: :date }
  validates :description, presence: true
  validates :image, url: true

  def self.sysReq(processor_rank, memory_rank, graphic_rank, offset, limit)
      sql = """
	    SELECT games.id, games.name, games.steam_id, games.price, games.release_date
	    FROM games
	    INNER JOIN system_requirements
	    ON games.id = system_requirements.game_id
	    INNER JOIN processors
	    ON system_requirements.processor_id = processors.id
	    WHERE processors.rank >= #{processor_rank}
	    INTERSECT
	    SELECT games.id, games.name, games.steam_id, games.price, games.release_date
	    FROM games
	    INNER JOIN system_requirements
	    ON games.id = system_requirements.game_id
	    INNER JOIN memories
	    ON system_requirements.memory_id = memories.id
	    WHERE memories.rank >= #{memory_rank}
	    INTERSECT
	    SELECT games.id, games.name, games.steam_id, games.price, games.release_date
	    FROM games
	    INNER JOIN system_requirements
	    ON games.id = system_requirements.game_id
	    INNER JOIN graphics
	    ON system_requirements.graphic_id = graphics.id
	    WHERE graphics.rank >= #{graphic_rank} offset #{offset} limit #{limit}
      """
      ActiveRecord::Base.connection.select_rows(sql)
  end


end

app/models/gamer.rb
class Gamer < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :gamername, presence: true, length: { maximum: 30 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 5 },allow_nil: true
  has_many :messages, dependent: :destroy
  # has_many :comments, dependent: :destroy

  has_many :game_ratings
  has_many :games, through: :game_ratings

  has_many :comments
  has_many :games, through: :comments, dependent: :destroy

  has_and_belongs_to_many :games
  has_many :likes, dependent: :destroy
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_and_belongs_to_many :games
end

app/models/graphic.rb
class Graphic < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :gamer
    belongs_to :game
    
    validates_uniqueness_of :gamer, scope: :game
  end

app/models/memory.rb
class Memory < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :gamer
  validates :content, presence: true
  validates :gamer_id, presence: true
  def self.most_recent
    order(:created_at).last(20)
  end
end

app/models/price_history.rb
class PriceHistory < ApplicationRecord
  belongs_to :game
end

app/models/processor.rb
class Processor < ApplicationRecord
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :gamer
end

app/models/system_requirement.rb
class SystemRequirement < ApplicationRecord
  belongs_to :game
  belongs_to :processor
  belongs_to :graphic
  belongs_to :memory
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  skip_before_action :verify_authenticity_token, raise: false
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  before_action :require_admin, only: [:create, :new, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
		@counts = ActiveRecord::Base.connection.execute('select count(*) from companies_games group by company_id order by company_id').values
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title = '')
    base_title = 'GTrack'
    if page_title.empty?
      base_title
    else
      page_title + ' | ' + base_title
    end
  end
    def gravatar_for(gamer, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(gamer.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: gamer.gamername, class: "img-circle")
  end

end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/companies/_form.html.erb
<%= form_with(model: company, local: true) do |form| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :company_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<% provide(:title, 'Companies') %>
<p id="notice"><%= notice %></p>

<h1 class="text-center">Companies</h1>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Game Count</th>
      <% if session[:gamer_id] and session[:user_type] == "admin" %>
      <th colspan="2">Options</th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @companies.zip(@counts).each do |company, count| %>
      <tr>
        <td><%= link_to company.name, company %></td>
        <td><%= count %></td>
        <% if session[:gamer_id] and session[:user_type] == "admin" %>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if session[:gamer_id] and session[:user_type] == "admin" %>
<%= link_to 'New Company', new_genre_path %>
<% end %>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<% provide(:title, @company.name) %>
<p id="notice"><%= notice %></p>

<h1 class="text-center"><%= @company.name.capitalize %> Games</h1>

<div class="clearfix clearfix-divider"></div>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Steam ID</th>
      <th>Price (USD)</th>
      <th>Release date</th>
    </tr>
  </thead>
  <tbody>
    <% @company.games.each do |game| %>
      <tr>
	<td><%= link_to game.name, game %></td>
	<td><%= link_to game.steam_id, "https://store.steampowered.com/app/#{game.steam_id}", target: "_blank" %></td>
	<td><%= game.price %></td>
	<td><%= game.release_date %></td>
      </tr>
    <% end %>
  </tbody>
</table>