config/routes.rb
Rails.application.routes.draw do
  resources :backgrounds
  resources :cards
  resources :emotes
  get 'static_pages/about'
  root "pages#home"
  get 'pages/home', to: 'pages#home'
  #root :to => "games#index"

  resources :games do
    resources :comments, only: [:create]
    member do 
      post 'like'
    end
  end

  get 'search_pages/search'
  post 'search_pages/search'
  get '/register', to: 'gamers#new'
  get "/signup", to: 'gamers#new'
  get '/login', to: 'sessions#new'
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"
  resources :gamers, except: [:new]

  resources :games
  resources :genres
  resources :companies
  mount ActionCable.server => '/cable'
  get '/chat', to: 'chatrooms#show'
  resources :messages, only: [:create]
  get '/games/stats/:id', to: 'games#stats'
  get '/games/loadmoresysreq/:processor/:memory/:graphic/:offset/:limit', to: 'games#loadmoresysreq'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/background.rb
class Background < ApplicationRecord
  belongs_to :game, optional: true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :game
  #validates :name, presence: true
  #validates :price, presence: true
  #validates :image, presence: true
  #validates :game_id, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :gamer
  belongs_to :game 
  # validates :description, presence: true, length: { minimum: 4, maximum: 140 }
  # validates :gamer_id, presence: true
  # validates :game_id, presence: true
  # default_scope -> { order(updated_at: :desc)}
end

app/models/company.rb
class Company < ApplicationRecord
    has_and_belongs_to_many :games
end

app/models/emote.rb
class Emote < ApplicationRecord
  belongs_to :game
end

app/models/game.rb
class Game < ApplicationRecord

  has_one :system_requirement

  has_many :backgrounds
  has_many :cards
  has_many :emotes

  has_and_belongs_to_many :companies

  has_many :game_ratings
  has_many :gamers, through: :game_ratings
  
  has_many :comments, dependent: :destroy
  has_many :gamers, through: :comments

  has_many :price_histories

  has_and_belongs_to_many :genres
  has_and_belongs_to_many :gamers
  has_many :likes, dependent: :destroy
  def thumbs_up_total
    self.likes.where(like: true).size
  end
  
  def thumbs_down_total
    self.likes.where(like: false).size    
  end
 
  validates :steam_id, presence: true, numericality: {only_integer: true}, uniqueness: true
  validates :name, presence: true
  validates :price, presence: true, numericality: true
  validates :release_date, presence: true, timeliness: { type: :date }
  validates :description, presence: true
  validates :image, url: true

  def self.sysReq(processor_rank, memory_rank, graphic_rank, offset, limit)
      sql = """
	    SELECT games.id, games.name, games.steam_id, games.price, games.release_date
	    FROM games
	    INNER JOIN system_requirements
	    ON games.id = system_requirements.game_id
	    INNER JOIN processors
	    ON system_requirements.processor_id = processors.id
	    WHERE processors.rank >= #{processor_rank}
	    INTERSECT
	    SELECT games.id, games.name, games.steam_id, games.price, games.release_date
	    FROM games
	    INNER JOIN system_requirements
	    ON games.id = system_requirements.game_id
	    INNER JOIN memories
	    ON system_requirements.memory_id = memories.id
	    WHERE memories.rank >= #{memory_rank}
	    INTERSECT
	    SELECT games.id, games.name, games.steam_id, games.price, games.release_date
	    FROM games
	    INNER JOIN system_requirements
	    ON games.id = system_requirements.game_id
	    INNER JOIN graphics
	    ON system_requirements.graphic_id = graphics.id
	    WHERE graphics.rank >= #{graphic_rank} offset #{offset} limit #{limit}
      """
      ActiveRecord::Base.connection.select_rows(sql)
  end


end

app/models/gamer.rb
class Gamer < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :gamername, presence: true, length: { maximum: 30 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 5 },allow_nil: true
  has_many :messages, dependent: :destroy
  # has_many :comments, dependent: :destroy

  has_many :game_ratings
  has_many :games, through: :game_ratings

  has_many :comments
  has_many :games, through: :comments, dependent: :destroy

  has_and_belongs_to_many :games
  has_many :likes, dependent: :destroy
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_and_belongs_to_many :games
end

app/models/graphic.rb
class Graphic < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :gamer
    belongs_to :game
    
    validates_uniqueness_of :gamer, scope: :game
  end

app/models/memory.rb
class Memory < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :gamer
  validates :content, presence: true
  validates :gamer_id, presence: true
  def self.most_recent
    order(:created_at).last(20)
  end
end

app/models/price_history.rb
class PriceHistory < ApplicationRecord
  belongs_to :game
end

app/models/processor.rb
class Processor < ApplicationRecord
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :gamer
end

app/models/system_requirement.rb
class SystemRequirement < ApplicationRecord
  belongs_to :game
  belongs_to :processor
  belongs_to :graphic
  belongs_to :memory
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  skip_before_action :verify_authenticity_token, raise: false
  before_action :set_card, only: [:show, :edit, :update, :destroy]
  before_action :require_admin, only: [:create, :new, :edit, :update, :destroy]

  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.all
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        game = Game.find(params[:card][:game_id])
	game.cards << @card
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.require(:card).permit(:name, :price, :image, :game_id, :foil)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title = '')
    base_title = 'GTrack'
    if page_title.empty?
      base_title
    else
      page_title + ' | ' + base_title
    end
  end
    def gravatar_for(gamer, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(gamer.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: gamer.gamername, class: "img-circle")
  end

end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/cards/_form.html.erb
<%= form_with(model: card, local: true) do |form| %>
  <% if card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_area :name, id: :card_name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price, id: :card_price %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_area :image, id: :card_image %>
  </div>

  <div class="field">
    <%= form.label :game_id %>
    <%= form.number_field :game_id, id: :card_steam_id %>
  </div>

  <div class="field">
    <input type="hidden" name="card[foil]" value="false">
    <label><input type="checkbox" name="card[foil]" value="true"> foil</label>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<h1>Editing Card</h1>

<%= render 'form', card: @card %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cards</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Image</th>
      <th>Foil</th>
      <% if logged_in? && current_gamer.admin? %>
      <th colspan="2">Options</th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @cards.each do |card| %>
      <tr>
        <td><%= link_to card.name, card %></td>
        <td><%= card.price %></td>
        <td><img style="max-width: 200px" src="<%= card.image %>"></td>
	<td><% if card.foil == true %>Yes<% else %>No<% end %></td>
	<% if logged_in? && current_gamer.admin? %>
        <td><%= link_to 'Edit', edit_card_path(card) %></td>
        <td><%= link_to 'Destroy', card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	<% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Card', new_card_path %>

app/views/cards/new.html.erb
<h1>New Card</h1>

<%= render 'form', card: @card %>

<%= link_to 'Back', cards_path %>

app/views/cards/show.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-center">card <span class="game-header"><%= @card.name %></span> for <span class="game-header"><%= @card.game.name %></span></h1>

<p class="text-center">
  <strong>Price:</strong>
  <%= @card.price %>
</p>

<p class="text-center">
  <img src="<%= @card.image %>" style="max-width: 500px">
</p>


<p class="text-center">
<% if @card.foil == true %><span class="badge badge-primary">FOIL CARD</span><% end %>
</p>

<p class="text-center">
  <a href="/games/<%= @card.game_id %>"">[visit <%= @card.game.name %> page]</a>
</p>

<% if logged_in? && current_gamer.admin? %>
<%= link_to 'Edit', edit_card_path(@card) %> |
<%= link_to 'Back', cards_path %>
<% end %>